### ISSUE TITLE
Table des migrations supprimée lors de l'exécution des tests

### ISSUE THREAD

**Issue by steve-caillault** [steve-caillault/nascar-symfony#5]
Lors de l'exécution des tests PHPUnit, le chargement de Fixtures supprime la tables des migrations.
Le problème peut être résolu en ajoutant dans la configuration framework.yaml :

````yaml
when@test:
    liip_test_fixtures:
        keep_database_and_schema: true
````
